# Generated by Django 5.1.1 on 2024-10-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_alter_article_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(to="blog.category", verbose_name="دسته بندی"),
        ),
    ]
