# Generated by Django 5.1.1 on 2024-10-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_category_options_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_special",
            field=models.BooleanField(default=False, verbose_name="مقاله ویژه"),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("d", "پیش نویس"),
                    ("p", "منتشرشده"),
                    ("i", "در حال بررسی"),
                    ("b", "برگشت داده شده"),
                ],
                max_length=1,
                verbose_name="وضعیت",
            ),
        ),
    ]
